INSERT INTO FIT5042.HOTEL_USER (USERID, USERTYPE, CITY, COUNTRY, EMAIL, FIRSTNAME, LASTNAME, PASSWORD, PHONE, POSTCODE, STREET, USERNAME, BALANCE, TYPECODE) 
	VALUES (1, 'admin', 'Melbourne', 'Australia', 'admin@hotel.com', 'Ricky', 'Li', '8C6976E5B5410415BDE908BD4DEE15DFB167A9C873FC4BB8A81F6F2AB448A918', '900000000', '3008', 'Collin', 'admin', NULL, 'User');
INSERT INTO FIT5042.HOTEL_TRANSACTION_TYPE (TYPECODE, TYPEDESC, TYPENAME) 
	VALUES (1, 'Cash', 'Cash');
INSERT INTO FIT5042.HOTEL_TRANSACTION_TYPE (TYPECODE, TYPEDESC, TYPENAME) 
	VALUES (2, 'Credit Card', 'Credit Card');
INSERT INTO FIT5042.HOTEL_TRANSACTION_TYPE (TYPECODE, TYPEDESC, TYPENAME) 
	VALUES (3, 'Paypel', 'Paypel');
INSERT INTO FIT5042.HOTEL_TRANSACTION_TYPE (TYPECODE, TYPEDESC, TYPENAME) 
	VALUES (4, 'Alipay', 'Alipay');
 FIT5042.HOTEL_ROOM_TYPE (TYPEID, TYPEDESC, TYPENAME) 
	VALUES (1, 'single room', 'Single');
INSERT INTO FIT5042.HOTEL_ROOM_TYPE (TYPEID, TYPEDESC, TYPENAME) 
	VALUES (2, 'Double Room', 'Double');
INSERT INTO FIT5042.HOTEL_ROOM_TYPE (TYPEID, TYPEDESC, TYPENAME) 
	VALUES (3, 'Family Room', 'Family');
INSERT INTO FIT5042.HOTEL_ROOM (ROOMID, PRICE, ROOMAVALIABLE, ROOMDESC, ROOMTYPE) 
	VALUES (1, 12.0, 1, 'single', 1);
INSERT INTO FIT5042.HOTEL_ROOM (ROOMID, PRICE, ROOMAVALIABLE, ROOMDESC, ROOMTYPE) 
	VALUES (2, 25.0, 1, 'double', 2);
INSERT INTO FIT5042.HOTEL_ROOM (ROOMID, PRICE, ROOMAVALIABLE, ROOMDESC, ROOMTYPE) 
	VALUES (3, 50.0, 1, 'familly', 3);


